### ISSUE TITLE
NeedHelp: Error during json processing

### ISSUE THREAD

**Issue by Feilner** [TheNytangel/Synology-LetsEncrypt-Remote-Update#3]
It seems I have trouble with the line

`login_response = requests.get(base_url + login_endpoint, params=login_query).json()`

It seems that the .json() is causing the error. When I remove it the login_response contains. `<Response [200]>`

Here is the complete printout
```
root@swag.mynetwork.xyz:/etc/letsencrypt/renewal-hooks/deploy# python3 ./Synology-LetsEncrypt-Remote-Update/synology.py /config/keys/letsencrypt/privkey.pem /config/keys/letsencrypt/fullchain.pem
Traceback (most recent call last):
  File "./Synology-LetsEncrypt-Remote-Update/synology.py", line 92, in <module>
    if update_certificate(sys.argv[1], sys.argv[2]) and not requests.get(base_url + login_endpoint, params=logout_query, cookies=cookies).json()["success"]:
  File "./Synology-LetsEncrypt-Remote-Update/synology.py", line 42, in update_certificate
    login_response = requests.get(base_url + login_endpoint, params=login_query).json()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

I have also added some debug output of the impute values these are:
```
certificate_cn: *.mynetwork.xyz
base_url: https://synology.mynetwork.xyz (tried also with http)
login_endpoint: /webapi/auth.cgi
login_query: {'api': 'SYNO.API.Auth', 'version': '3', 'method': 'login', 'session': 'Certificate', 'format': 'sid', 'account': 'myuser', 'passwd': 'mypassword'}
```
All listed reqired phyton modules are installed but in newer versions.

Do you have any idea whats wrong?

**Comment by TheNytangel** [comment]
Are you able to do
```
login_response = requests.get(base_url + login_endpoint, params=login_query)
print(login_response.text)
```
in order to get the actual response data? It would be useful to tell what's wrong.

**Comment by Feilner** [comment]
Thanks for your willing to help!

As requested the print out of your mentioned call:

login_response = requests.get(base_url + login_endpoint, params=login_query)
print(login_response.text)
```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=11" />
<meta name="msapplication-TileImage" content="resources/images/icon_tile.png?v=4398" />
<meta name="application-name" content="Synology&nbsp;-&nbsp;Synology&nbsp;NAS" />
<meta name="msapplication-TileColor" content="#246BB3"/>
<meta name="description" content="Synology NAS provides a full-featured network attached storage (NAS) solution to help you manage, backup and share data among Windows, Mac and Linux easily." />
<meta name="keywords" content="Multitasking,Web Application,Personal Cloud" />

<link rel="apple-touch-icon" href="webman/resources/images/icon_dsm_96.png?v=4398" />
<link rel="mask-icon" href="webman/safari_pin_icon.svg" color="#0086E5" />
<link rel="shortcut icon" href="webman/favicon.ico?v=4399" />
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_96.png?v=4398" sizes="96x96"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_64.png?v=4398" sizes="64x64"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_48.png?v=4398" sizes="48x48"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_32.png?v=4398" sizes="32x32"/>
<link rel="shortcut icon" href="webman/resources/images/icon_dsm_16.png?v=4398" sizes="16x16"/>
<title>Synology&nbsp;-&nbsp;Synology&nbsp;NAS</title>
<link rel="stylesheet" type="text/css" href="scripts/ext-3/resources/css/ext-all.css?v=1589234961" />
<link rel="stylesheet" type="text/css" href="scripts/ext-3/resources/css/xtheme-gray.css?v=1589234961" />
<link rel="stylesheet" type="text/css" href="scripts/ext-3/ux/ux-all.css?v=1617346099" />
<link rel="stylesheet" type="text/css" href="synoSDSjslib/sds.css?v=1617346099" />
<link rel="stylesheet" type="text/css" href="webman/resources/css/desktop.css?v=1617346099" />
<style type="text/css">
@import url("webman/modules/PhotoViewer/style.css?v=1589235149");
@import url("webman/modules/ResourceMonitor/style.css?v=1589235149");
@import url("webman/modules/VideoPlayer2/style.css?v=1589235141");
@import url("webman/modules/WelcomeApp/style.css?v=1589235149");
@import url("webman/modules/PersonalSettings/style.css?v=1589235149");
@import url("webman/modules/TaskSchedulerUtils/style.css?v=1589235149");
@import url("webman/modules/AudioPlayer/style.css?v=1589235148");
@import url("webman/modules/EzInternet/style.css?v=1589235149");
@import url("webman/modules/MyDSCenter/style.css?v=1589235149");
@import url("webman/modules/C3/style.css?v=1589235149");
@import url("webman/modules/ConfigBackup/style.css?v=1589235144");
@import url("webman/modules/DSMNotify/style.css?v=1589235149");
@import url("webman/modules/PollingTask/style.css?v=1589235150");
@import url("webman/modules/HotkeyManager/style.css?v=1589235149");
@import url("webman/modules/Utils/style.css?v=1589235148");
@import url("webman/modules/DiskMessageHandler/style.css?v=1589235149");
@import url("webman/modules/Widgets/style.css?v=1589235149");
@import url("webman/modules/AdminCenter/style.css?v=1589235184");
@import url("webman/modules/StorageManager/style.css?v=1589235149");
@import url("webman/modules/ExternalDevices/style.css?v=1589235149");
@import url("webman/modules/LogCenter/style.css?v=1589235128");
@import url("webman/modules/WelcomeTip/style.css?v=1589235150");
@import url("webman/modules/iSCSI/style.css?v=1589234968");
@import url("webman/modules/SystemInfoApp/style.css?v=1589235149");
@import url("webman/modules/BandwidthControl/style.css?v=1589234968");
@import url("webman/modules/PkgManApp/style.css?v=1589235149");
@import url("webman/modules/SecurityScan/style.css?v=1589235171");
@import url("webman/modules/HelpBrowser/style.css?v=1589235149");
@import url("webman/modules/FileTaskMonitor/style.css?v=1612254374");
@import url("webman/modules/ThumbConvertProgress/style.css?v=1589235171");
</style>
<style type="text/css">
@import url("webman/modules/DataDrivenDocuments/style.css?v=1589235149");
@import url("webman/modules/FileBrowser/style.css?v=1612254380");
@import url("webman/modules/ClipBoardJS/style.css?v=1589235148");
@import url("webman/modules/Share/style.css?v=1589235149");
@import url("webman/modules/TaskSchedulerWidget/style.css?v=1589235149");
@import url("webman/modules/SupportForm/style.css?v=1589235149");
</style>
<link rel="stylesheet" type="text/css" href="webman/3rdparty/USBCopy/style.css?v=1589543033" />
<link rel="stylesheet" type="text/css" href="webman/3rdparty/OAuthService/style.css?v=1609749254" />
<link rel="stylesheet" type="text/css" href="webman/3rdparty/MediaServer/style.css?v=1613706384" />
<link rel="stylesheet" type="text/css" href="webman/3rdparty/ActiveBackup/style.css?v=1607318805" />
<link rel="stylesheet" type="text/css" href="webman/3rdparty/SynoFinder/style.css?v=1611317769" />
<link rel="stylesheet" type="text/css" href="webman/3rdparty/ActiveBackup-Portal/style.css?v=1607318799" />

</head>
<body role="application">
<div id="sds-wallpaper"></div>
<!-- Don't contain any text node to avoid IE insertBefore bug -->
<div id="sds-login-dialog-form" style="position: absolute; top: -10000px; left: -10000px;"><form id="login-form" class="x-plain-body" method="POST" action="webman/login.cgi" target="login_iframe"><input type="text" class="x-form-text" id="login_username" name="username" maxlength="256" /><input type="password" class="x-form-text" id="login_passwd" name="passwd" maxlength="256" autocomplete="off" /><input class="x-form-text" type="text" id="login_otp" name="OTPcode" maxlength="8" autocomplete="off" /><input type="submit" id="login_submit" style="position: absolute; top: -10000px; left: -10000px;" tabindex="-1" /></form><iframe id="login_iframe" name="login_iframe" width="0" height="0" frameborder="0" style="display: none;"></iframe></div>
<div id="sds-apply-preview-form" style="position: absolute; top: -10000px; left: -10000px;"><form id="preview-form" class="x-plain-body" method="POST" action="webman/modules/ControlPanel/modules/dsm.cgi" target="preview_iframe"><input type="submit" id="preview_submit" style="position: absolute; top: -10000px; left: -10000px;" tabindex="-1" /></form><iframe id="preview_iframe" name="preview_iframe" width="0" height="0" frameborder="0" style="display: none;"></iframe></div>
<script type="text/javascript" src="webapi/entry.cgi?api=SYNO.Core.Desktop.Defs&version=1&method=getjs&v=1601472835"></script>
<script type="text/javascript" src="webapi/entry.cgi?api=SYNO.Core.Desktop.JSUIString&version=1&method=getjs&lang=enu&v=1601470791"></script>
<script type="text/javascript" src="webapi/entry.cgi?api=SYNO.Core.Desktop.UIString&version=1&method=getjs&lang=enu&v=1601470791"></script>
<script type="text/javascript" src="scripts/prototype-1.7.2/prototype.js?v=1589234961"></script>
<script type="text/javascript" src="scripts/ext-3/adapter/ext/ext-base.js?v=1589234961"></script>
<script type="text/javascript" src="scripts/ext-3/ext-all.js?v=1589234961"></script>
<script type="text/javascript" src="scripts/ext-3/ux/ux-all.js?v=1589234961"></script>
<script type="text/javascript" src="scripts/scrollbar/flexcroll.js?v=1589234961"></script>
<script type="text/javascript" src="synoSDSjslib/sds.js?v=1589234966"></script>
<script type="text/javascript" src="webman/desktop.js?v=1607944358"></script>
<script type="text/javascript" src="webapi/entry.cgi?api=SYNO.Core.Desktop.SessionData&version=1&method=getjs&SynoToken=&v=1589235139"></script>

<script type="text/javascript" src="webman/security.cgi"></script>
<div class="pre-load-x-window-br"></div>
</body>
<noscript><div class='syno-no-script'><div class='title align-center'>This page can't be displayed</div><div class='desc align-center'>Please allow your browser to run JavaScript.</div><div class='icon align-center'></div></div></noscript>
</html>
```

**Comment by TheNytangel** [comment]
Can you try change `login_endpoint = "/webapi/auth.cgi"` to `login_endpoint = "/webapi/entry.cgi"`?
